### ISSUE TITLE
Custom build command failure due to missing autoreconf (j9-sys v0.1.2) 

### ISSUE THREAD

**Issue by TieWay59** [ynqa/j9#1]
**Description**:
I am experiencing an issue when attempting to compile the `j9-sys v0.1.2` crate. The custom build command fails with the following error message:

```
error: failed to run custom build command for `j9-sys v0.1.2`
Caused by:
  process didn't exit successfully: `/tmp/cargo-installsCL7B6/release/build/j9-sys-acd45b9a421ac1f9/build-script-build` (exit status: 101)
  --- stderr
  autoreconf: 1: exec: autoreconf: not found
  ...
```

**Actual Result**:
The build process fails, with an error indicating that `autoreconf` is not installed on the system.

**Environment Information**:
- Operating System: Ubuntu 22.04
- Rust version: rustc 1.76.0 (07dca489a 2024-02-04)
- Cargo version: 1.76.0 (c84b36747 2024-01-18)

**Feedback**:
It seems that the build script for `j9-sys` depends on `autoreconf`, which is not always present on all platforms. This leads to compilation failure on systems where `autoreconf` is not pre-installed.

**Suggestions**:
I recommend adding a check in the build script to verify the presence of `autoreconf` and to provide clear instructions or automated steps for users to install it if it's missing. Furthermore, it would be beneficial if the crate's documentation included a note about the requirement of `autoreconf` and how users can address this dependency.

Thank you for considering this feedback. I believe that improved environment checks and prompts will greatly enhance the user experience when working with the `j9-sys` crate.

**Comment by TieWay59** [comment]
Hi @ynqa, I came from your jnv project, this is what I met while building jnv in my PC. I think it's better to describe your system deps before user install it, it took me some time to guess around the required deps.

**Comment by ynqa** [comment]
@TieWay59 Thank you for detailing the situation. 🙏 

As you mentioned, there indeed is a dependency on autoreconf/automake (it had been installed on my laptop for so long that I completely overlooked it).

Based on what has been outlined in the suggestions, it's clear we need to devise a strategy to address this issue.

Thank you once again for your report.

**Comment by TieWay59** [comment]
Glad to help. @ynqa

FYI, you can try to build it in a very basic docker image to figure out the minimum dependency set.
